# Generated by Django 6.0.1 on 2026-02-04 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_open", models.BooleanField(default=True)),
                ("results_published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Question Type",
                "verbose_name_plural": "Question Types",
                "db_table": "question_types",
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "db_table": "teams",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(primary_key=True, serialize=False),
                ),
                ("question", models.TextField()),
                ("points", models.IntegerField(blank=True, null=True)),
                ("default_answer", models.IntegerField(default=0)),
                ("actual_answer", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="questions",
                        to="core.questiontype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MultipleChoice",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("choice", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="choices",
                        to="core.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multiple Choice",
                "verbose_name_plural": "Multiple Choices",
                "db_table": "multiple_choices",
                "ordering": ["question", "order"],
                "indexes": [
                    models.Index(
                        fields=["question", "order"],
                        name="multiple_ch_questio_153485_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "order"),
                        name="uniq_choice_per_question_order",
                    ),
                    models.UniqueConstraint(
                        fields=("question", "choice"),
                        name="uniq_choice_per_question_text",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="core.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="answers",
                        to="core.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Answer",
                "verbose_name_plural": "Answers",
                "db_table": "answers",
                "ordering": ["question", "user"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question"), name="uniq_answer_user_question"
                    )
                ],
            },
        ),
    ]
